### ISSUE TITLE
Link to guild?

### ISSUE THREAD

**Issue by samuell** [sparkslabs/kamaelia#1]
What is the link to Guild, the successor of Kamaelia? (It's a rather common word, so not easy to be sure to find the correct one)

**Comment by sparkslabs** [comment]
Hi, 

That's an interesting question - I hadn't thought about putting a forward link in - thanks for the feedback.

The main links to guild at present are:
- https://github.com/sparkslabs/guild - main repo
- http://www.sparkslabs.com/michael/blog/category/guild - blog posts I've written relating to guild
- http://www.sparkslabs.com/guild/ - place holder website - generated from the repo - cf https://github.com/sparkslabs/guild/tree/master/site
- https://github.com/sparkslabs/guild-kamaelia - nascent compatibility layer - not really linked to anywhere yet because I don't think there's enough useful in there yet :-)

Guild is a play on Actor incidentally - an Actor's Guild.

As things go, the status of guild is that it's sufficiently useful for the things I need to use it for, and I've had some pull requests for bringing in things like python 3 support and so on.

I've added these to the README, with some additional notes.

If they look good, if you could close and comment, that'd be great :-)

Michael
